---
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: flake8
      - id: check-case-conflict
      - id: check-json
      - id: mixed-line-ending
      - id: check-merge-conflict

  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.11.1
    hooks:
      - id: yamllint

  # this pylint wrapper lets us set a required score
  - repo: git@github.com:coldnight/pre-commit-pylint.git
    rev: v0.0.3
    hooks:
      - id: pylint-score-limit
        args:
          - --limit=8.5
          - --rcfile=./.pylintrc

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.720
    hooks:
      - id: mypy
